/**
 * Design tokens extracted from kiksu-mobile-screens.html
 * Source: /Users/macbook/kiksu/design/kiksu-mobile-screens.html
 * Generated by mechanical extraction of inline styles
 */

// ============================================================================
// COLORS
// ============================================================================

export const colors = {
  // Primary / Interactive
  primary: '#0F7A85', // Şirvan turkuazı (primary/teal, 62 uses)
  primaryHover: '#0B5C64', // Teal darker state (9 uses)
  primaryLight: '#F0F7F7', // Teal tint background (9 uses)
  primaryAccent: '#9ECBCF', // Teal accent/border (9 uses)
  primaryTint: '#E4F0F1', // Teal tint surface (3 uses)

  // Secondary / Bronze (course indicator, card tier)
  secondary: '#C8952A', // Tunc / kart (bronze, card tier, 10 uses)
  secondaryLight: '#FAF3E4', // Bronze light background (7 uses)
  secondaryLightBg: '#F6EFDF', // Bronze/tan background (4 uses)
  secondaryDark: '#8A6B21', // Bronze secondary text (10 uses)

  // Semantic / Urgent (deadlines, urgency)
  urgent: '#B23A2F', // Nar / son tarix (pomegranate, deadlines, 23 uses)
  urgentLight: '#F4E7E5', // Pomegranate light background (2 uses)
  urgentLightBg: '#FAF3F2', // Pink/light pomegranate (4 uses)
  urgentDark: '#8C2C23', // Pomegranate darker (4 uses)
  urgentLightStroke: '#E8D9D6', // Pomegranate light border (8 uses)
  urgentBorder: '#E8C9C4', // Pomegranate border (4 uses)

  // Accent / Course indicator (English/blue courses)
  accent: '#2F5A9E', // Blue for English language courses (7 uses)
  accentLight: '#C3CEE4', // Blue light (1 use)
  accentBg: '#EFEFF6', // Blue light background (4 uses)

  // Gray scale / Neutrals
  ink: '#141C24', // Xəzər mürəkkəbi (dark text/buttons, 23 uses)
  textPrimary: '#141C24', // Alias for ink (dark text)
  textSecondary: '#4A525C', // Secondary text (28 uses)
  textTertiary: '#5C6470', // Tertiary text (22 uses)
  textPlaceholder: '#8A9099', // Placeholder text (44 uses)
  textMuted: '#6D7580', // Muted/secondary labels (92 uses - most used)
  textMutedLight: '#9AA0A8', // Light muted text (21 uses)
  textDarkSecondary: '#3D444D', // Dark secondary (11 uses)

  // Backgrounds / Surfaces
  surface: '#FFFFFF', // White surface (54 uses)
  background: '#F1F0EC', // Bakı əhəngdaşı (light beige background, 11 uses)
  backgroundLight: '#F5F3EC', // Very light background (18 uses)
  backgroundLightest: '#FCFBF8', // Lightest background (1 use)
  backgroundWarm: '#F4F2EC', // Warm light (2 uses)
  backgroundWarmest: '#FAF6EC', // Warmest light (2 uses)
  backgroundCream: '#FBFAF7', // Cream (1 use)
  backgroundBeige: '#F7F6F2', // Beige (1 use)
  backgroundStone: '#EAE7DF', // Stone (1 use)
  backgroundUltraLight: '#E9E6DE', // Ultra light (1 use)
  backgroundPageBg: '#E7E5DF', // Page/document background (2 uses)
  backgroundWarmSurface: '#EFEDE6', // Warm surface (4 uses)

  // Borders / Strokes / Dividers
  border: '#DEDCD5', // Primary border (48 uses)
  borderLight: '#EDEBE4', // Light border (34 uses)
  borderLighter: '#E4E1D9', // Lighter border/divider (9 uses)
  borderLightest: '#F0EEE7', // Lightest divider (8 uses)
  borderCoarse: '#D6D3CA', // Coarse border (10 uses)
  borderLightStroke: '#E0DDD5', // Light stroke (7 uses)
  borderGrayLight: '#E4D3AC', // Tan/bronze light border (9 uses)
  scrollThumb: '#C7C4BB', // Scrollbar thumb color (6 uses)

  // Additional colors (used in timetable course indicators)
  timetableCourseA9: '#A9C7CA', // Course color variant (1 use)
  timetableCourseBrown: '#6B5518', // Course brown variant (1 use)
} as const;

export type Colors = typeof colors;

// ============================================================================
// TYPOGRAPHY
// ============================================================================

export const typography = {
  // Font families
  fontFamilies: {
    // System/Sans (default for body text)
    sans: "-apple-system, 'SF Pro Text', 'Segoe UI', Roboto, 'Noto Sans', 'Helvetica Neue', Arial, sans-serif",
    // Monospace (for eyebrow labels, data, metrics)
    mono: "ui-monospace, 'SF Mono', 'Segoe UI Mono', 'Roboto Mono', Menlo, monospace",
  },

  // Font scales (size, weight, letter-spacing combinations)
  // Eyebrow/Label (mono, small, uppercase)
  eyebrow: {
    xs: {
      fontSize: '9px',
      fontWeight: 700,
      letterSpacing: '.1em',
      fontFamily: 'mono',
    },
    sm: {
      fontSize: '10px',
      fontWeight: 700,
      letterSpacing: '.08em',
      fontFamily: 'mono',
    },
    base: {
      fontSize: '10px',
      fontWeight: 700,
      letterSpacing: '.06em',
      fontFamily: 'mono',
    },
    md: {
      fontSize: '11px',
      fontWeight: 700,
      letterSpacing: '.12em',
      fontFamily: 'mono',
    },
    lg: {
      fontSize: '11px',
      fontWeight: 700,
      letterSpacing: '.06em',
      fontFamily: 'mono',
    },
  },

  // Label/Caption (mono, used for secondary info)
  label: {
    xs: {
      fontSize: '8.5px',
      fontWeight: 700,
      letterSpacing: '.1em',
      fontFamily: 'mono',
    },
    sm: {
      fontSize: '9px',
      fontWeight: 700,
      fontFamily: 'mono',
    },
    base: {
      fontSize: '10px',
      fontWeight: 700,
      letterSpacing: '.06em',
      fontFamily: 'mono',
    },
    md: {
      fontSize: '11px',
      fontWeight: 700,
      letterSpacing: '.05em',
      fontFamily: 'mono',
    },
  },

  // Body text (sans-serif)
  body: {
    xs: {
      fontSize: '11px',
      fontWeight: 400,
      fontFamily: 'sans',
    },
    sm: {
      fontSize: '12px',
      fontWeight: 400,
      fontFamily: 'sans',
    },
    base: {
      fontSize: '14px',
      fontWeight: 400,
      fontFamily: 'sans',
    },
  },

  // Body/Text (semi-bold)
  bodyMedium: {
    sm: {
      fontSize: '12px',
      fontWeight: 600,
      fontFamily: 'sans',
    },
    base: {
      fontSize: '14px',
      fontWeight: 600,
      fontFamily: 'sans',
    },
    md: {
      fontSize: '15px',
      fontWeight: 600,
      fontFamily: 'sans',
    },
  },

  // Heading/Titles
  heading: {
    sm: {
      fontSize: '16px',
      fontWeight: 600,
      fontFamily: 'sans',
    },
    base: {
      fontSize: '19px',
      fontWeight: 700,
      fontFamily: 'sans',
    },
    md: {
      fontSize: '24px',
      fontWeight: 700,
      fontFamily: 'sans',
    },
    lg: {
      fontSize: '25px',
      fontWeight: 700,
      letterSpacing: '-0.025em',
      fontFamily: 'sans',
    },
    xl: {
      fontSize: '26px',
      fontWeight: 700,
      letterSpacing: '-0.02em',
      fontFamily: 'sans',
    },
    '2xl': {
      fontSize: '27px',
      fontWeight: 700,
      letterSpacing: '-0.025em',
      fontFamily: 'sans',
    },
  },

  // Display/Large
  display: {
    lg: {
      fontSize: '34px',
      fontWeight: 700,
      fontFamily: 'sans',
    },
  },

  // Letter spacing scale (used independently)
  letterSpacing: {
    tight: '-0.03em',
    tighter: '-0.025em',
    tightest: '-0.015em',
    tightish: '-0.02em',
    tightestAlt: '-0.01em',
    normal: '0em',
    loose: '.04em',
    looser: '.05em',
    looseMore: '.06em',
    loosest: '.08em',
    monoLabel: '.1em',
    monoMedium: '.12em',
    monoData: '.14em',
  },
} as const;

export type Typography = typeof typography;

// ============================================================================
// SPACING SCALE
// ============================================================================

export const spacing = {
  '0.5': '2px',
  '1': '3px',
  '1.5': '4px',
  '2': '5px',
  '2.5': '6px',
  '3': '7px',
  '3.5': '8px',
  '4': '10px',
  '5': '12px',
  '5.5': '14px',
  '6': '16px',
  '7': '20px',
  '8': '24px',
  '8.5': '26px',
  '9': '32px',
} as const;

export type Spacing = typeof spacing;

// ============================================================================
// BORDER RADIUS SCALE
// ============================================================================

export const radii = {
  xs: '2px',
  sm: '3px',
  base: '4px',
  md: '5px',
  lg: '6px',
  xl: '7px',
  '2xl': '9px',
  '3xl': '10px',
  full: '50%', // circles
  // Composite radii (for specific components)
  'pill-sm': '12px',
  'pill-md': '14px',
  'pill-lg': '16px',
  'modal-bottom': '24px 24px 42px 42px',
  'modal-bottom-alt': '12px 12px 0 0',
  'frame': '42px', // phone frame corners
} as const;

export type Radii = typeof radii;

// ============================================================================
// LAYOUT
// ============================================================================

export const layout = {
  // Mobile phone frame dimensions (10 screens in the mockup)
  mobileViewportWidth: 390,
  mobileViewportHeight: 844,

  // Derived constants
  phoneFrame: {
    width: 390,
    height: 844,
    borderRadius: 42,
  },

  // Status bar height (standard iOS)
  statusBarHeight: 46,

  // Tab/Navigation bar height
  navBarHeight: 80,
} as const;

export type Layout = typeof layout;

// ============================================================================
// COMPLETE DESIGN TOKENS EXPORT
// ============================================================================

export const tokens = {
  colors,
  typography,
  spacing,
  radii,
  layout,
} as const;

export type Tokens = typeof tokens;
